### ISSUE TITLE
Adding support for new Emoji

### ISSUE THREAD

**Issue by dannolan** [janlelis/unicode-emoji#2]
Hey there!

First off I absolutely love this library, it's so well organised and designed, it has been a total pleasure to use - thank you for your incredible work.

I'm just wondering, is there a straightforward way for me to update the marshal.gz file with newer emoji? I'm trying to build something that will match newer emoji and want to add them to one of the regexes.

I really love the project! Thank you for your hard work!

**Comment by janlelis** [comment]
Hi Dan,

thank you for your kind words and your feedback. I am using the unicoder gem to generate the `marshal.gz` file. It is not yet polished, however, you can already use it to create customized emoji indexes following these steps:

1) Clone the unicoder repository from: github.com/janlelis/unicoder and run bundler
2) The emoji builder is located here: https://github.com/janlelis/unicoder/blob/master/lib/unicoder/builders/emoji.rb. Customize the file to suit your needs. For example, you can add new emoji at the end of the `parse!` method to `@index`
3) Run the following command: 

```
$ bin/unicoder build emoji --gzip
Building index for emoji…
Index created at: emoji.marshal.gz (25745 bytes written)
```

4) Load the new index file into unicode-emoji

Feel free to share if this works for you or if you have further questions!

**Comment by dannolan** [comment]
@janlelis thank you so much!
